# 2021 Ernest
# Version
apiVersion: apps/v1
# This can be a statefulset, or a deployment, a deployment doesn't need a hard drive
kind: Deployment
metadata:
# This is the name of my deployment
  name: ernest-cit270
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ernest-cit270
  template:
    metadata:
      labels:
        app: ernest-cit270
    spec:
      containers:
        - name: ernest-cit270
        # This is the Dockerhud url to my image
          image: ernestdanso/cit270
        # This is the command to run once the container starts
          command: ["npm"]

          args: ["run","start"]

          ports:
            - containerPort: 3000
          resources:
            limits:

              cpu: ".125"

              memory: "500Mi"
            requests:

              cpu: ".1"

              memory: "250Mi"
          livenessProbe:
            httpGet:

              path: /

              port: 3000

              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:

              path: /

              port: 3000

              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3


---
apiVersion: v1
kind: Service
metadata:
  name: ernest-cit270-loadbalancer
spec:
  selector:
    app: ernest-cit270
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
